### ISSUE TITLE
LDAP: can share with users, but not with groups

### ISSUE THREAD

**Issue by joergmschulz** [juliushaertl/deck#50]
### Steps to reproduce

1. share a board to a LDAP group but not the individual users.
2. open the board with the userID belonging to that group
3. 

### Expected behavior
the board should open
paged search is not available for me - maybe the error results in this one?

### Actual behavior
Error message: Error occurred, fetching boards failed.
Console states: GET http://domain.org/nextcloud/index.php/apps/deck/boards/1 403 (Forbidden)
### Server configuration
**Operating system**:
Debian, lenny

**Web server:**
Apache 2.4
**Database:**
MySQL
**PHP version:**
7.0
**Server version:** (see your admin page)
11.01 and 11.02
**Deck version:** (see the apps page)
0.1.1 and compiled master of version of Feb 13

**Updated from an older installed version or fresh install:**
tried both

**Signing status:**

```
Login as admin user into your cloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your instance's installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

LDAP

### Client configuration
**Browser:**
Chrome, Iridium

**Operating system:**
OSX
#### Web server error log
```[Mon Feb 13 16:12:05.793260 2017] [:error] [pid 9906] [client 192.168.178.45:60670] PHP Fatal error:  Uncaught Doctrine\\DBAL\\DBALException: Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [2002] No such file or directory in /var/www/nextcloud/lib/private/DB/Connection.php:60\nStack trace:\n#0 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): OC\\DB\\Connection->connect()\n#1 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\\DBAL\\Connection->getDatabasePlatformVersion()\n#2 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\\DBAL\\Connection->detectDatabasePlatform()\n#3 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(621): Doctrine\\DBAL\\Connection->getDatabasePlatform()\n#4 /var/www/nextcloud/lib/private/DB/Connection.php(147): Doctrine\\DBAL\\Connection->setTransactionIsolation(2)\n#5 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php(172): OC\\DB\\Connection->__construct(Array, Object(Doctrine\\DBAL\\Driver\\PDOMySql\\Driver), Obj in /var/www/nextcloud/lib/private/DB/Connection.php on line 60
[Mon Feb 13 16:12:05.865273 2017] [:error] [pid 9906] [client 192.168.178.45:60670] PHP Fatal error:  Uncaught Doctrine\\DBAL\\DBALException: Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [2002] No such file or directory in /var/www/nextcloud/lib/private/DB/Connection.php:60\nStack trace:\n#0 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): OC\\DB\\Connection->connect()\n#1 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\\DBAL\\Connection->getDatabasePlatformVersion()\n#2 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\\DBAL\\Connection->detectDatabasePlatform()\n#3 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(621): Doctrine\\DBAL\\Connection->getDatabasePlatform()\n#4 /var/www/nextcloud/lib/private/DB/Connection.php(147): Doctrine\\DBAL\\Connection->setTransactionIsolation(2)\n#5 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php(172): OC\\DB\\Connection->__construct(Array, Object(Doctrine\\DBAL\\Driver\\PDOMySql\\Driver), Obj in /var/www/nextcloud/lib/private/DB/Connection.php on line 60
[Mon Feb 13 16:12:05.881276 2017] [:error] [pid 9862] [client 192.168.178.45:60938] PHP Fatal error:  Uncaught Doctrine\\DBAL\\DBALException: Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [2002] No such file or directory in /var/www/nextcloud/lib/private/DB/Connection.php:60\nStack trace:\n#0 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): OC\\DB\\Connection->connect()\n#1 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\\DBAL\\Connection->getDatabasePlatformVersion()\n#2 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\\DBAL\\Connection->detectDatabasePlatform()\n#3 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(621): Doctrine\\DBAL\\Connection->getDatabasePlatform()\n#4 /var/www/nextcloud/lib/private/DB/Connection.php(147): Doctrine\\DBAL\\Connection->setTransactionIsolation(2)\n#5 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php(172): OC\\DB\\Connection->__construct(Array, Object(Doctrine\\DBAL\\Driver\\PDOMySql\\Driver), Obj in /var/www/nextcloud/lib/private/DB/Connection.php on line 60
[Mon Feb 13 16:12:05.881276 2017] [:error] [pid 9862] [client 192.168.178.45:60938] PHP Fatal error:  Uncaught Doctrine\\DBAL\\DBALException: Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [2002] No such file or directory in /var/www/nextcloud/lib/private/DB/Connection.php:60\nStack trace:\n#0 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): OC\\DB\\Connection->connect()\n#1 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\\DBAL\\Connection->getDatabasePlatformVersion()\n#2 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\\DBAL\\Connection->detectDatabasePlatform()\n#3 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(621): Doctrine\\DBAL\\Connection->getDatabasePlatform()\n#4 /var/www/nextcloud/lib/private/DB/Connection.php(147): Doctrine\\DBAL\\Connection->setTransactionIsolation(2)\n#5 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php(172): OC\\DB\\Connection->__construct(Array, Object(Doctrine\\DBAL\\Driver\\PDOMySql\\Driver), Obj in /var/www/nextcloud/lib/private/DB/Connection.php on line 60
[Mon Feb 13 16:12:08.461698 2017] [mpm_prefork:notice] [pid 611] AH00169: caught SIGTERM, shutting down
[Mon Feb 13 16:12:36.219052 2017] [mpm_prefork:notice] [pid 562] AH00163: Apache/2.4.25 (Debian) OpenSSL/1.0.2k configured -- resuming normal operations
[Mon Feb 13 16:12:36.239053 2017] [core:notice] [pid 562] AH00094: Command line: '/usr/sbin/apache2'
Insert your webserver log here
```

#### Log file (data/nextcloud.log)
```
"Ready for a paged search","level":0,"time":"2017-02-13T18:12:15+00:00","method":"GET","url":"\/nextcloud\/index.php\/apps\/deck\/boards\/1","user":"some.body","version":"11.0.2.0"}
{"reqId":"yMmSWYb3f7+X0PpX4u88","remoteAddr":"192.168.178.45","app":"user_ldap","message":"initializing paged search for  Filter (&(objectclass=groupOfNames)(&(businessCategory=cloud))) base Array\n(\n    [0] => cn=some correct Ldap CN\n)\n attr Array\n(\n    [0] => cn\n)\
n limit 500 offset 0","level":0,"time":"2017-02-13T18:12:15+00:00","method":"GET","url":"\/nextcloud\/index.php\/apps\/deck\/boards\/1","user":"some.body","version":"11.0.2.0"}
```

**Comment by juliushaertl** [comment]
@joergmschulz Thanks for the detailed report. b5feeeaee309d6b576c513a66edf4d8a7c3d49d1 should fix that. It would be great if you could verify. You need to remove and add the group to the board to apply the changes.

**Comment by joergmschulz** [comment]
Confirm: The fix does work like expected. You can close this issue now.
Thank you for all your work and for fixing this one.
